// ==UserScript==
// @name         AGARLUCKY V1.1
// @description  I WANTED TO SAY THIS SCRIPT WILL BE POSTED SOON WHEN I DO TO CONTROL MOUSE EXPECT IF YOU HAVE ANY QUESTIONS ASK!
// @match        http://agar.io/*
// @require      https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.6/socket.io.min.js
// @require      http://pastebin.com/raw/aDMxfr3Q
// @grant        none
// @run-at       document-start
// ==/UserScript==
